### ISSUE TITLE
The explaination of some key features in the dataset.

### ISSUE THREAD

**Issue by al00014** [ihmeuw/dismod_mr#19]
Dear developers and fellow workers in the dismod_mr project,
I have read your example and are working on the example you provided. However, in the dismod_mr, the dataset input_data.csv does not give too much detailed description of the data. Say there are a bunch of different column names, but it is really hard to read understand each meaning.

eg.	age_start	age_weights	area	data_type	effective_sample_size	lower_ci	sex	standard_error	upper_ci	value	x_cv_ascertainment	x_cv_diagnostic_criteria	x_cv_representative	year_end	year_start

Also, I have a hard time working with the pycppad package because I could not get it working properly. But that's another issue than.

Thank you!

**Comment by aflaxman** [comment]
`pycppad` is a nightmare to install, but it is possible!  Let's have a completely separate ticket for that if you figure out how to do it and want to share your insight for future users.

My apologies for the lack of documentation on the columns in the `input_data.csv` examples.  Here is something that might help you figure things out, unfortunately from a slightly earlier iteration of the format:
```
Name	Type	Limit
Cause	str	None
Region	str	one of the GBD regions
Param	str	‘continuous single parameter’
Sex  	str	male or female
Country	str	an ISO3 code in the region
Age Start	int	[0, 100], <= Age End
Age End	int	[0, 100], >= Age Start
Year Start	int	[1980, 2010], <= Year End
Year End	int	[1980, 2010], >= Year Start
Value	float	>= 0
Units	float	>= 1
Standard Error	float	>=0
```

**Comment by aflaxman** [comment]
in `input_data.csv` these are all from data that someone has collected (almost never me!).  The predicted values will be produced after analysis.  `effective_sample_size` is a good way to quantify uncertainty in these measurements, but `standard_error` or `(lower_ci, upper_ci)` is more common in the literature, in my experience.

`x_cv_ascertainment` is a "study-level covariate" coding for how case ascertainment was handled in each study.  Similar story for `x_cv_diagnostic_criteria` and `x_cv_representative`.

**Comment by al00014** [comment]
Thank you very much for your instruction!

**Comment by aflaxman** [comment]
You are welcome. Please continue to ask questions like this if they come up, I'm sure this could be useful to others as well!
