### ISSUE TITLE
Dismod_mr does not install on M1 Macs

### ISSUE THREAD

**Issue by arinbasu** [ihmeuw/dismod_mr#41]
I tried to install dismod_mr based on the instructions posted on the DISMOD_MR website. Unfortunately for M1 Macs, it is impossible to install python 3.6 using conda. The rest of it does not work anyway. Is it possible to update the codes so that we can use later version of python and pymc please?

**Comment by aflaxman** [comment]
Unfortunately PyMC2 is not compatible with later versions, so it is a larger project than I will be able to take on to update these codes. :(

I have heard of others tangling with this issue as well. I don't use Macs well enough to test it out for myself, but perhaps one of the users who interacted with [issue #36 after we figured out the version problem](https://github.com/ihmeuw/dismod_mr/issues/36#issuecomment-1454355965) will have an answer for you.
